import Head from 'next/head'
import About from '../components/About'
import Inquiry from '../components/Inquiry'
import Skills from '../components/Skills'
import WelcomeSection from '../components/WelcomeSection'
import Work from '../components/Work'

export default function Home() {
  return (
    <div>
      <Head>
        <title>fullstack123</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
       
       <div className="">
     
       {/* first section */}
       <section className=" container">
      <WelcomeSection/>
       </section>
       <section>
       <Skills/>
       <Work/>
       <About/>
       <Inquiry/>
        </section>
       
       </div>
    </div>
  )
}
